#!/usr/bin/env python3
"""Pack the Latin glyphs cropped from PSBBN's skbKey.png into LUNA's font format."""

from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "res/gfx/psbbn_latin_source.png"
HEADER = ROOT / "include/ui/psbbn_font.h"
FIRST, LAST = 32, 126
ATLAS_WIDTH, ATLAS_HEIGHT = 256, 256
EXTRA_CHARS = sorted(set("¡¿ÀÁÂÃÇÉÊÍÑÓÔÕÚÜàáâãçéêíñóôõúü"), key=ord)
# The keyboard texture puts these descenders unusually high in their cells.
# Align their lowercase bodies and let their tails fall below the baseline.
DESCENDER_OFFSETS = {"g": 2, "p": 1, "q": 1, "y": 1}


def main():
    source = Image.open(SOURCE).convert("RGBA")
    assert source.size == (256, 96)
    atlas = Image.new("RGBA", (ATLAS_WIDTH, ATLAS_HEIGHT), (255, 255, 255, 0))
    glyphs = [(0, 0, 1, 1, 0, 0, 5)]  # Space.
    x, y = 1, 1
    codes = list(range(FIRST, LAST + 1)) + [ord(c) for c in EXTRA_CHARS]
    for code in codes[1:]:
        char = chr(code)
        parts = unicodedata.normalize("NFD", char)
        base = parts[0] if len(parts) == 2 else char
        inverted = char in "¡¿"
        if inverted:
            base = "!" if char == "¡" else "?"
        # Accented glyphs retain the PSBBN keyboard's native letter shapes.
        source_code = ord(base)
        index = source_code - FIRST - 1
        cell_x, cell_y = index % 16 * 16, index // 16 * 16
        cell = source.crop((cell_x, cell_y, cell_x + 16, cell_y + 16))
        bounds = cell.getchannel("A").getbbox()
        if bounds is None:
            raise ValueError(f"Missing PSBBN glyph: {chr(code)!r}")
        left, top, right, bottom = bounds
        width, height = right - left, bottom - top
        pixels = cell.crop(bounds)
        yoffset = top + 2 + DESCENDER_OFFSETS.get(base, 0)
        if inverted:
            pixels = pixels.transpose(Image.Transpose.ROTATE_180)
        elif len(parts) == 2:
            accent = parts[1]
            if accent == '\u0327':  # Cedilla below the original C/c.
                combined = Image.new("RGBA", (width, height + 3))
                combined.paste(pixels, (0, 0))
                draw = ImageDraw.Draw(combined)
                mid = width // 2
                draw.line([(mid, height), (mid + 1, height + 1), (mid - 1, height + 2)], fill="white")
            else:
                combined = Image.new("RGBA", (width, height + 4))
                combined.paste(pixels, (0, 4))
                draw = ImageDraw.Draw(combined)
                mid = width // 2
                if accent == '\u0301': draw.line([(mid - 1, 2), (mid + 1, 0)], fill="white")
                elif accent == '\u0300': draw.line([(mid - 1, 0), (mid + 1, 2)], fill="white")
                elif accent == '\u0302': draw.line([(mid - 2, 2), (mid, 0), (mid + 2, 2)], fill="white")
                elif accent == '\u0303': draw.line([(mid - 2, 1), (mid - 1, 0), (mid + 1, 1), (mid + 2, 0)], fill="white")
                elif accent == '\u0308':
                    draw.rectangle((mid - 2, 0, mid - 1, 1), fill="white")
                    draw.rectangle((mid + 1, 0, mid + 2, 1), fill="white")
                else: raise ValueError(f"Unsupported accent: {char}")
                yoffset -= 4
            pixels = combined
            width, height = pixels.size
        if x + width + 1 >= ATLAS_WIDTH:
            x, y = 1, y + 20
        if y + height + 1 >= ATLAS_HEIGHT:
            raise ValueError("PSBBN Latin atlas overflow")
        atlas.paste(pixels, (x, y))
        glyphs.append((x, y, width, height, 0,
                       yoffset, width + 2))
        x += width + 2  # Empty texels protect adjacent glyphs from GS sampling.

    encoded = BytesIO()
    atlas.save(encoded, format="PNG", optimize=True)
    data = encoded.getvalue()
    byte_rows = ["  " + ", ".join(f"0x{byte:02x}" for byte in data[i:i + 16]) + ","
                 for i in range(0, len(data), 16)]
    rows = [f"  {{{gx}, {gy}, {w}, {h}, {xo}, {yo}, {advance}, 0, 0, 15, NULL}},"
            for gx, gy, w, h, xo, yo, advance in glyphs]
    buckets = ["{32, 126, BMFONT_PSBBN_CHARS}"] + [
        f"{{{ord(char)}, {ord(char)}, BMFONT_PSBBN_CHARS + {95 + i}}}"
        for i, char in enumerate(EXTRA_CHARS)]
    HEADER.write_text("""// Generated by tools/generate_psbbn_font.py from psbbn_latin_source.png.
#ifndef _UI_PSBBN_FONT_H_
#define _UI_PSBBN_FONT_H_
// Include after dejavu_sans.h, which defines the shared BMFont types.
unsigned char BMFONT_PSBBN_PAGE_0[];
const BMFontChar BMFONT_PSBBN_CHARS[] = {
""" + "\n".join(rows) + "\n};\n" + f"""const BMFontBucket BMFONT_PSBBN_BUCKETS[] = {{{', '.join(buckets)}}};
const BMFontPage BMFONT_PSBBN_PAGES[] = {{{{{len(data)}, BMFONT_PSBBN_PAGE_0}}}};
const BMFont BMFONT_PSBBN = {{
  .scaleW = {ATLAS_WIDTH}, .scaleH = {ATLAS_HEIGHT}, .size = 16, .lineHeight = 20, .base = 16, .isPacked = 0,
  .aChannelType = CHANNEL_GLYPH, .rChannelType = CHANNEL_ONE,
  .gChannelType = CHANNEL_ONE, .bChannelType = CHANNEL_ONE,
  .bucketCount = {len(buckets)}, .buckets = BMFONT_PSBBN_BUCKETS,
  .pageCount = 1, .pages = BMFONT_PSBBN_PAGES,
}};
unsigned char BMFONT_PSBBN_PAGE_0[] __attribute__((aligned(16))) = {{
""" + "\n".join(byte_rows) + "\n};\n#endif\n", encoding="ascii", newline="\n")
    print(f"Packed {len(glyphs)} Latin glyphs into {len(data)} PNG bytes")


if __name__ == "__main__":
    main()
