#!/usr/bin/env python3
"""Pack the Latin glyphs cropped from PSBBN's skbKey.png into LUNA's font format."""

from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "res/gfx/psbbn_latin_source.png"
HEADER = ROOT / "include/ui/psbbn_font.h"
FIRST, LAST = 32, 126
ATLAS_WIDTH, ATLAS_HEIGHT = 256, 128
# The keyboard texture puts these descenders unusually high in their cells.
# Align their lowercase bodies and let their tails fall below the baseline.
DESCENDER_OFFSETS = {"g": 2, "p": 1, "q": 1, "y": 1}


def main():
    source = Image.open(SOURCE).convert("RGBA")
    assert source.size == (256, 96)
    atlas = Image.new("RGBA", (ATLAS_WIDTH, ATLAS_HEIGHT), (255, 255, 255, 0))
    glyphs = [(0, 0, 1, 1, 0, 0, 5)]  # Space.
    x, y = 1, 1
    for code in range(FIRST + 1, LAST + 1):
        index = code - FIRST - 1
        cell_x, cell_y = index % 16 * 16, index // 16 * 16
        cell = source.crop((cell_x, cell_y, cell_x + 16, cell_y + 16))
        bounds = cell.getchannel("A").getbbox()
        if bounds is None:
            raise ValueError(f"Missing PSBBN glyph: {chr(code)!r}")
        left, top, right, bottom = bounds
        width, height = right - left, bottom - top
        if x + width + 1 >= ATLAS_WIDTH:
            x, y = 1, y + 20
        if y + height + 1 >= ATLAS_HEIGHT:
            raise ValueError("PSBBN Latin atlas overflow")
        atlas.paste(cell.crop(bounds), (x, y))
        glyphs.append((x, y, width, height, 0,
                       top + 2 + DESCENDER_OFFSETS.get(chr(code), 0), width + 2))
        x += width + 2  # Empty texels protect adjacent glyphs from GS sampling.

    encoded = BytesIO()
    atlas.save(encoded, format="PNG", optimize=True)
    data = encoded.getvalue()
    byte_rows = ["  " + ", ".join(f"0x{byte:02x}" for byte in data[i:i + 16]) + ","
                 for i in range(0, len(data), 16)]
    rows = [f"  {{{gx}, {gy}, {w}, {h}, {xo}, {yo}, {advance}, 0, 0, 15, NULL}},"
            for gx, gy, w, h, xo, yo, advance in glyphs]
    HEADER.write_text("""// Generated by tools/generate_psbbn_font.py from psbbn_latin_source.png.
#ifndef _UI_PSBBN_FONT_H_
#define _UI_PSBBN_FONT_H_
// Include after dejavu_sans.h, which defines the shared BMFont types.
unsigned char BMFONT_PSBBN_PAGE_0[];
const BMFontChar BMFONT_PSBBN_CHARS[] = {
""" + "\n".join(rows) + "\n};\n" + f"""const BMFontBucket BMFONT_PSBBN_BUCKETS[] = {{{{32, 126, BMFONT_PSBBN_CHARS}}}};
const BMFontPage BMFONT_PSBBN_PAGES[] = {{{{{len(data)}, BMFONT_PSBBN_PAGE_0}}}};
const BMFont BMFONT_PSBBN = {{
  .scaleW = 256, .scaleH = 128, .size = 16, .lineHeight = 20, .base = 16, .isPacked = 0,
  .aChannelType = CHANNEL_GLYPH, .rChannelType = CHANNEL_ONE,
  .gChannelType = CHANNEL_ONE, .bChannelType = CHANNEL_ONE,
  .bucketCount = 1, .buckets = BMFONT_PSBBN_BUCKETS,
  .pageCount = 1, .pages = BMFONT_PSBBN_PAGES,
}};
unsigned char BMFONT_PSBBN_PAGE_0[] __attribute__((aligned(16))) = {{
""" + "\n".join(byte_rows) + "\n};\n#endif\n", encoding="ascii")
    print(f"Packed {len(glyphs)} Latin glyphs into {len(data)} PNG bytes")


if __name__ == "__main__":
    main()
