#!/usr/bin/env python3
# Original LUNA code: Danny Nunez (dnunezx) 2026
"""Generate Luna's hinted, CRT-weight bitmap font atlas and C header."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "res/gfx/DejaVu Sans/ttf/DejaVuSans.ttf"
OUT_DIR = ROOT / "res/gfx/DejaVu Sans/bmfont"
HEADER_PATH = ROOT / "include/ui/dejavu_sans.h"
ATLAS_SIZE = 256
RASTER_SIZE = 17
LINE_HEIGHT = 20
BASELINE = 15
FIRST_CHAR = 32
LAST_CHAR = 126


def c_bytes(data):
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16]) + ",")
    return "\n".join(rows)


def main():
    font = ImageFont.truetype(str(FONT_PATH), RASTER_SIZE)
    atlas = Image.new("RGBA", (ATLAS_SIZE, ATLAS_SIZE), (255, 255, 255, 0))
    draw = ImageDraw.Draw(atlas)
    glyphs = []
    x, y = 4, 1  # Keep (1,1) transparent for the space glyph.
    row_height = LINE_HEIGHT + 2

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        char = chr(code)
        advance = max(1, round(font.getlength(char)))
        if char == " ":
            glyphs.append((1, 1, 1, LINE_HEIGHT, 0, 0, advance))
            continue

        left, top, right, bottom = font.getbbox(char, anchor="ls", stroke_width=1)
        width = right - left
        height = bottom - top
        if x + width + 2 > ATLAS_SIZE:
            x = 1
            y += row_height
        if y + LINE_HEIGHT + 1 > ATLAS_SIZE:
            raise RuntimeError("Font atlas overflow")

        # FreeType supplies native-size hinting. A translucent one-pixel outer
        # stroke produces a semibold weight without the bloom of a full bold face.
        draw.text((x - left, y - top), char, font=font, anchor="ls", fill=(255, 255, 255, 255),
                  stroke_width=1, stroke_fill=(255, 255, 255, 104))
        glyphs.append((x, y, width, height, left, BASELINE + top, advance))
        x += width + 2

    png_path = OUT_DIR / "dejavusans_0.png"
    atlas.save(png_path, optimize=True)
    png_data = png_path.read_bytes()

    kernings = {}
    for first in range(FIRST_CHAR, LAST_CHAR + 1):
        pairs = []
        first_char = chr(first)
        first_width = font.getlength(first_char)
        for second in range(FIRST_CHAR, LAST_CHAR + 1):
            amount = round(font.getlength(first_char + chr(second)) - first_width - font.getlength(chr(second)))
            if amount:
                pairs.append((second, amount))
        if pairs:
            kernings[first] = pairs

    fnt_lines = [
        'info face="DejaVu Sans CRT Semibold" size=20 bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=2,2 outline=0',
        f"common lineHeight={LINE_HEIGHT} base={BASELINE} scaleW={ATLAS_SIZE} scaleH={ATLAS_SIZE} pages=1 packed=0 alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4",
        'page id=0 file="dejavusans_0.png"',
        f"chars count={len(glyphs)}",
    ]
    for code, glyph in zip(range(FIRST_CHAR, LAST_CHAR + 1), glyphs):
        gx, gy, width, height, xoff, yoff, advance = glyph
        fnt_lines.append(
            f"char id={code:<3} x={gx:<3} y={gy:<3} width={width:<2} height={height:<2} "
            f"xoffset={xoff:<2} yoffset={yoff:<2} xadvance={advance:<2} page=0 chnl=15"
        )
    (OUT_DIR / "dejavusans.fnt").write_text("\n".join(fnt_lines) + "\n", encoding="ascii")

    parts = ["""// Generated by tools/generate_crt_font.py
// LUNA font generation: Danny Nunez (dnunezx) 2026
#ifndef _UI_DEJAVU_SANS_H_
#define _UI_DEJAVU_SANS_H_

#ifndef _BMFONT_TYPES_
#define _BMFONT_TYPES_
#include <stddef.h>
#include <stdint.h>
typedef struct BMFontKerning { uint32_t secondChar; int16_t amount; } BMFontKerning;
typedef struct BMFontChar {
  uint16_t x, y, width, height;
  int16_t xoffset, yoffset, xadvance;
  uint8_t page, kerningsCount, channels;
  const BMFontKerning *kernings;
} BMFontChar;
typedef struct BMFontBucket { uint32_t startChar, endChar; const BMFontChar *chars; } BMFontBucket;
typedef struct BMFontPage { unsigned int size; unsigned char *data; } BMFontPage;
typedef enum { CHANNEL_GLYPH, CHANNEL_OUTLINE, CHANNEL_GLYPH_OUTLINE, CHANNEL_ZERO, CHANNEL_ONE } ChannelType;
typedef struct BMFont {
  uint16_t scaleW, scaleH, size;
  uint8_t lineHeight, base, isPacked;
  ChannelType aChannelType, rChannelType, gChannelType, bChannelType;
  uint16_t bucketCount; const BMFontBucket *buckets;
  uint16_t pageCount; const BMFontPage *pages;
} BMFont;
#endif

unsigned char BMFONT_DEJAVU_SANS_PAGE_0[];
"""]
    for code, pairs in kernings.items():
        entries = ", ".join(f"{{{second}, {amount}}}" for second, amount in pairs)
        parts.append(f"const BMFontKerning BMFONT_DEJAVU_SANS_KERNINGS_CHAR_{code}[] = {{{entries}}};\n")

    parts.append("\nconst BMFontChar BMFONT_DEJAVU_SANS_BUCKET_0[] = {\n")
    for code, glyph in zip(range(FIRST_CHAR, LAST_CHAR + 1), glyphs):
        gx, gy, width, height, xoff, yoff, advance = glyph
        pairs = kernings.get(code, [])
        pointer = f"BMFONT_DEJAVU_SANS_KERNINGS_CHAR_{code}" if pairs else "NULL"
        parts.append(f"  {{{gx}, {gy}, {width}, {height}, {xoff}, {yoff}, {advance}, 0, {len(pairs)}, 15, {pointer}}},\n")
    parts.append("""};
const BMFontBucket BMFONT_DEJAVU_SANS_BUCKETS[] = {{32, 126, BMFONT_DEJAVU_SANS_BUCKET_0}};
const BMFontPage BMFONT_DEJAVU_SANS_PAGES[] = {{FONT_PNG_SIZE, BMFONT_DEJAVU_SANS_PAGE_0}};
const struct BMFont BMFONT_DEJAVU_SANS = {
  .scaleW = 256, .scaleH = 256, .size = 20, .lineHeight = 20, .base = 15, .isPacked = 0,
  .aChannelType = CHANNEL_GLYPH, .rChannelType = CHANNEL_ONE,
  .gChannelType = CHANNEL_ONE, .bChannelType = CHANNEL_ONE,
  .bucketCount = 1, .buckets = BMFONT_DEJAVU_SANS_BUCKETS,
  .pageCount = 1, .pages = BMFONT_DEJAVU_SANS_PAGES,
};
unsigned char BMFONT_DEJAVU_SANS_PAGE_0[] __attribute__((aligned(16))) = {
FONT_PNG_BYTES
};
#endif
""")
    header = "".join(parts).replace("FONT_PNG_SIZE", str(len(png_data))).replace("FONT_PNG_BYTES", c_bytes(png_data))
    HEADER_PATH.write_text(header, encoding="ascii")


if __name__ == "__main__":
    main()
